# version: '3'



# services:
#   spark-master:
#     image: my-custom-spark:latest
#     container_name: spark-master-container
#     command: /bin/bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master"
#     hostname: spark-master
#     ports:
#       - "8080:8080"  # Spark Master UI
#       - "7077:7077"  # Master to Worker communication
#       - "4040:4040"
    

#   spark-worker-1:
#     image: my-custom-spark:latest
#     container_name: spark-worker-1-container
#     command: /bin/bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
#     depends_on:
#       - spark-master

#   spark-worker-2:
#     image: my-custom-spark:latest
#     container_name: spark-worker-2-container
#     command: /bin/bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
#     depends_on:
#       - spark-master


version: '3'

services:
  spark-local:
    image: my-vanilla-spark:latest
    container_name: vanilla-spark-local-container
    command: tail -f /dev/null  # Keeps the container running
    ports:
      - "8080:8080"  # Spark UI


